# Email Configuration
spring.mail.host=mail.privateemail.com
spring.mail.port=465
spring.mail.protocol=smtps
spring.mail.username=support@nexusasm.com
spring.mail.password=nexPrivTrin@098
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# Frontend URL for links in emails
app.frontend-url=nexusasm.com

security.jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
security.jwt.expiration-time=3600000
security.jwt.refresh-token.expiration-time=604800000

# Use the service name 'db' (Docker network DNS) instead of localhost
# spring.datasource.username=ld_admin
# spring.datasource.password=mAnAgyA1
# spring.datasource.driver-class-name=org.postgresql.Driver
spring.application.name=lambdarcore
spring.profiles.active=ldadmin
# spring.datasource.url=jdbc:postgresql://localhost:5432/lambdar_db
spring.datasource.url=jdbc:postgresql://34.23.233.51:5432/lambdar_db
spring.datasource.username=ld_admin
spring.datasource.password=mAnAgyA1

# Schema initialization
spring.jpa.hibernate.ddl-auto=update
spring.datasource.continue-on-error=true
spring.datasource.initialization-mode=always
spring.datasource.initialization=true
spring.datasource.schema=classpath:/migration.sql

# HikariCP connection pool configuration
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=2000000
spring.datasource.hikari.connection-timeout=30000


springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# File Upload Configuration
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# Google Cloud Storage
# Credentials
#spring.cloud.gcp.project-id=deployment-testing-460522
#google.application.credentials=file:/app/credentials.json
#spring.cloud.gcp.credentials.location=file:/app/credentials.json
#spring.cloud.gcp.storage.credentials.location=file:/app/credentials.json

# Upload Directories
google.cloud.storage.bucket=nexus-asset
app.assets.upload.dir=assets
app.profiles.upload.dir=profiles

app.base.url=https://ymca-studia-be-338912908752.us-east1.run.app

# Create upload directory on startup
spring.jpa.defer-datasource-initialization=true
spring.web.resources.add-mappings=false
