"""Seed catalogue for YMCA admin roles and permissions."""

from typing import Dict, Iterable, List, Tuple

# (name, group, description)
PERMISSION_CATALOGUE: List[Tuple[str, str, str]] = [
    ("admin_users.view", "Admin Users", "View admin user accounts"),
    ("admin_users.create", "Admin Users", "Create admin user accounts"),
    ("admin_users.update", "Admin Users", "Update admin user accounts"),
    ("admin_users.deactivate", "Admin Users", "Deactivate admin user accounts"),
    ("admin_users.reset_password", "Admin Users", "Reset admin user passwords"),
    ("roles.view", "Roles & Permissions", "View roles and permissions"),
    ("roles.create", "Roles & Permissions", "Create custom roles"),
    ("roles.update", "Roles & Permissions", "Update roles"),
    ("roles.delete", "Roles & Permissions", "Delete custom roles"),
    ("roles.assign_permissions", "Roles & Permissions", "Assign permissions to roles"),
    ("members.view", "Members", "View member profiles"),
    ("members.update", "Members", "Update member profiles"),
    ("members.delete", "Members", "Delete or deactivate members"),
    ("news.view", "News", "View news posts"),
    ("news.create", "News", "Create news posts"),
    ("news.update", "News", "Update news posts"),
    ("news.delete", "News", "Delete news posts"),
    ("programs.view", "Programs", "View programs"),
    ("programs.create", "Programs", "Create programs"),
    ("programs.update", "Programs", "Update programs"),
    ("programs.delete", "Programs", "Delete programs"),
    ("forms.view", "Forms", "View forms"),
    ("forms.create", "Forms", "Create forms"),
    ("forms.update", "Forms", "Update forms"),
    ("forms.delete", "Forms", "Delete forms"),
    ("notifications.view", "Notifications", "View notifications"),
    ("notifications.send", "Notifications", "Send notifications"),
    ("finance.view", "Finance", "View financial records"),
    ("finance.manage", "Finance", "Manage payments and payouts"),
    ("settings.view", "Settings", "View system settings"),
    ("settings.update", "Settings", "Update system settings"),
    ("analytics.view", "Progress", "View progress dashboards"),
    ("messages.view", "Messages", "View messages"),
    ("messages.send", "Messages", "Send messages"),
    ("vhs.view", "Volunteer Hours", "View volunteer hours submissions"),
    ("vhs.review", "Volunteer Hours", "Review and approve volunteer hours submissions"),
    ("branches.view", "Branches", "View regions and branches"),
    ("branches.create", "Branches", "Create regions and branches"),
    ("branches.update", "Branches", "Update regions, branches, and assign presidents"),
]

SYSTEM_ROLES: List[Tuple[str, str]] = [
    (
        "super_admin",
        "Platform developer / creator with full access to the YMCA admin system.",
    ),
    (
        "national_admin",
        "National-level administrator who can manage admins and oversee all regions.",
    ),
    (
        "regional_admin",
        "Regional administrator scoped to an assigned YMCA region.",
    ),
    (
        "branch_admin",
        "Branch administrator scoped to an assigned YMCA branch.",
    ),
]

ROLE_PERMISSIONS: Dict[str, Iterable[str]] = {
    "super_admin": [p[0] for p in PERMISSION_CATALOGUE],
    "national_admin": [
        "admin_users.view",
        "admin_users.create",
        "admin_users.update",
        "admin_users.deactivate",
        "admin_users.reset_password",
        "roles.view",
        "members.view",
        "members.update",
        "members.delete",
        "news.view",
        "news.create",
        "news.update",
        "news.delete",
        "programs.view",
        "programs.create",
        "programs.update",
        "programs.delete",
        "forms.view",
        "forms.create",
        "forms.update",
        "forms.delete",
        "notifications.view",
        "notifications.send",
        "finance.view",
        "finance.manage",
        "settings.view",
        "settings.update",
        "analytics.view",
        "messages.view",
        "messages.send",
        "vhs.view",
        "vhs.review",
        "branches.view",
        "branches.create",
        "branches.update",
    ],
    "regional_admin": [
        "members.view",
        "members.update",
        "news.view",
        "news.create",
        "news.update",
        "news.delete",
        "programs.view",
        "programs.create",
        "programs.update",
        "programs.delete",
        "forms.view",
        "forms.create",
        "forms.update",
        "forms.delete",
        "notifications.view",
        "notifications.send",
        "analytics.view",
        "messages.view",
        "messages.send",
        "vhs.view",
        "vhs.review",
        "branches.view",
    ],
    "branch_admin": [
        "members.view",
        "members.update",
        "news.view",
        "programs.view",
        "forms.view",
        "notifications.view",
        "messages.view",
        "messages.send",
        "vhs.view",
        "vhs.review",
        "branches.view",
    ],
}

# Roles a given actor role may assign when creating/updating admin users.
ASSIGNABLE_ROLES: Dict[str, Iterable[str]] = {
    "super_admin": ["super_admin", "national_admin", "regional_admin", "branch_admin"],
    "national_admin": ["regional_admin", "branch_admin"],
    "regional_admin": [],
    "branch_admin": [],
}

LEGACY_ROLE_MAP = {
    "SUPER_ADMIN": "super_admin",
    "ADMIN": "national_admin",
    "NATIONAL_ADMIN": "national_admin",
    "REGIONAL_ADMIN": "regional_admin",
    "BRANCH_ADMIN": "branch_admin",
    "EDITOR": "regional_admin",
    "MODERATOR": "branch_admin",
}
